package:
  name: dtocean-economics
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas

test:
  # Python imports
  imports:
    - dtocean_economics

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/DTOcean/dtocean-economics
  license: GPLv3
  license_file: LICENSE.txt
  summary: Economics module for the DTOcean tools

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
